In [15]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
movies = pd.read_csv("/content/Movies_dataset.csv")
movies.head()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811

In [5]:
movies.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [6]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10000 non-null  int64
 1   title              10000 non-null  object
 2   genre              9997 non-null   object
 3   original_language  10000 non-null  object
 4   overview           9987 non-null   object
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 703.3+ KB

In [8]:
movies['tags'] =movies['overview'] + movies['genre']
movies.head()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count,tags
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811,In the continuing saga of the Corleone crime f...

In [13]:
movies_new =movies[['id', 'title', 'tags']]

In [14]:
movies_new.head()

,id,title,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...

In [23]:
#converts text into a bag-of-words (BoW) model, keep top 100 words and remove english stop words
cv = CountVectorizer(max_features=1000, stop_words='english')

In [24]:
cv

CountVectorizer(max_features=1000, stop_words='english')

In [41]:
##learn vocabulary from data converted to array, Unicode format ('U'), ensuring text compatibility
vec = cv.fit_transform(movies_new['tags'].values.astype('U')).toarray()

In [26]:
vec

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [27]:
vec.shape

(10000, 1000)

In [43]:
#Computes cosine similarity between all movie vectors.#Values range from 0 (no similarity) to 1 (identical text content)
sim = cosine_similarity(vec)

In [30]:
sim

array([[1.        , 0.10114435, 0.20851441, ..., 0.11616046, 0.16718346,
        0.09325048],
       [0.10114435, 1.        , 0.14552138, ..., 0.        , 0.06482037,
        0.        ],
       [0.20851441, 0.14552138, 1.        , ..., 0.03713907, 0.1069045 ,
        0.13416408],
       ...,
       [0.11616046, 0.        , 0.03713907, ..., 1.        , 0.04962917,
        0.04152274],
       [0.16718346, 0.06482037, 0.1069045 , ..., 0.04962917, 1.        ,
        0.05976143],
       [0.09325048, 0.        , 0.13416408, ..., 0.04152274, 0.05976143,
        1.        ]])

In [32]:
movies_new[movies_new['title'] == 'The Shawshank Redemption']

,id,title,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...

In [33]:
dist = sorted(list(enumerate(sim[0])), reverse=True, key=lambda vec:vec[1])

In [34]:
dist

[(0, 1.0000000000000002),
 (2991, 0.39405520311955033),
 (698, 0.38306543884143696),
 (1009, 0.3640126041546321),
 (9006, 0.3611575592573076),
 (1264, 0.35564337957950964),
 (3709, 0.3478260869565218),
 (4811, 0.34752402342845795),
 (4064, 0.3382550457458692),
 (6162, 0.3348554112644579),
 (9520, 0.3348554112644579),
 (3649, 0.3296902366978935),
 (4201, 0.3263766828841098),
 (725, 0.31524416249564025),
 (2626, 0.31524416249564025),
 (2758, 0.31524416249564025),
 (6327, 0.3143473067309657),
 (7478, 0.30851602658597743),
 (2963, 0.3045547950507524),
 (5508, 0.30434782608695654),
 (1223, 0.3009646327144231),
 (2120, 0.3009646327144231),
 (5428, 0.297939785765562),
 (884, 0.2948839123097943),
 (1039, 0.2948839123097943),
 (5168, 0.29488391230979427),
 (5193, 0.29488391230979427),
 (8043, 0.29488391230979427),
 (6093, 0.2895702534395041),
 (1619, 0.28915746598312014),
 (3507, 0.28915746598312014),
 (5290, 0.28915746598312014),
 (9475, 0.28915746598312014),
 (9818, 0.28915746598312014),
 (4406, 0.2870189239409639),
 (715, 0.2862512870383358),
 (1646, 0.27975144247209416),
 (2498, 0.27975144247209416),
 (2766, 0.27975144247209416),
 (4999, 0.27975144247209416),
 (7878, 0.27975144247209416),
 (2084, 0.27863910628767646),
 (7271, 0.27863910628767646),
 (9756, 0.27863910628767646),
 (2605, 0.27801921874276636),
 (6909, 0.27801921874276636),
 (1175, 0.2730094531159741),
 (825, 0.26919095102908275),
 (7558, 0.26919095102908275),
 (2945, 0.2680899609305247),
 (1068, 0.2667325346846322),
 (1480, 0.2637521893583148),
 (2927, 0.2637521893583148),
 (3848, 0.2637521893583148),
 (3884, 0.2637521893583148),
 (4068, 0.2637521893583148),
 (7851, 0.2637521893583148),
 (3042, 0.26086956521739135),
 (5776, 0.26086956521739135),
 (6538, 0.26086956521739135),
 (552, 0.26064301757134345),
 (7071, 0.26064301757134345),
 (1918, 0.25802342327107),
 (834, 0.2553769592276246),
 (1773, 0.2553769592276246),
 (3159, 0.2553769592276246),
 (4271, 0.2553769592276246),
 (8911, 0.2553769592276246),
 (52, 0.25438520029955736),
 (7324, 0.25408390302421974),
 (7153, 0.25286086871208685),
 (2426, 0.2528608687120868),
 (6243, 0.2528608687120868),
 (9718, 0.2528608687120868),
 (1038, 0.2514778453847726),
 (2925, 0.2514778453847726),
 (4378, 0.2514778453847726),
 (4569, 0.2514778453847726),
 (4632, 0.2514778453847726),
 (4864, 0.2514778453847726),
 (6758, 0.2514778453847726),
 (7049, 0.2514778453847726),
 (8424, 0.2514778453847726),
 (5587, 0.25021729686848976),
 (196, 0.2502172968684897),
 (9139, 0.2467175818975845),
 (4234, 0.24573659359149527),
 (7921, 0.24573659359149527),
 (8503, 0.24573659359149527),
 (153, 0.24573659359149524),
 (279, 0.24535824603285925),
 (4490, 0.24535824603285925),
 (8760, 0.24535824603285922),
 (540, 0.24077170617153845),
 (919, 0.24077170617153845),
 (1034, 0.24077170617153845),
 (1130, 0.24077170617153845),
 (1133, 0.24077170617153845),
 (1331, 0.24077170617153845),
 (1407, 0.24077170617153845),
 (1615, 0.24077170617153845),
 (2081, 0.24077170617153845),
 (4063, 0.24077170617153845),
 (4347, 0.24077170617153845),
 (4491, 0.24077170617153845),
 (4563, 0.24077170617153845),
 (5434, 0.24077170617153845),
 (6074, 0.24077170617153845),
 (6294, 0.24077170617153845),
 (7207, 0.24077170617153845),
 (7828, 0.24077170617153845),
 (8800, 0.24077170617153845),
 (1507, 0.23918243661746993),
 (4273, 0.23918243661746993),
 (8555, 0.23918243661746993),
 (1787, 0.2391824366174699),
 (1834, 0.2391824366174699),
 (4295, 0.2391824366174699),
 (1697, 0.23643312187173018),
 (2456, 0.23643312187173018),
 (2616, 0.23643312187173018),
 (3114, 0.23643312187173018),
 (3670, 0.23643312187173018),
 (4574, 0.23643312187173018),
 (4987, 0.23643312187173018),
 (5027, 0.23643312187173018),
 (8832, 0.23643312187173018),
 (9599, 0.23643312187173018),
 (3611, 0.23312620206007845),
 (4765, 0.23312620206007845),
 (6418, 0.23312620206007845),
 (7116, 0.23312620206007845),
 (8071, 0.23312620206007845),
 (393, 0.2323209277987099),
 (663, 0.2323209277987099),
 (5985, 0.2323209277987099),
 (6284, 0.2323209277987099),
 (1105, 0.2313259727864961),
 (1657, 0.2313259727864961),
 (2522, 0.2313259727864961),
 (2796, 0.2313259727864961),
 (3508, 0.2313259727864961),
 (4222, 0.2313259727864961),
 (4608, 0.2313259727864961),
 (5571, 0.2313259727864961),
 (6756, 0.2313259727864961),
 (7471, 0.2313259727864961),
 (7884, 0.2313259727864961),
 (1343, 0.2284160962880643),
 (2624, 0.22750787759664506),
 (3269, 0.22750787759664506),
 (4953, 0.22750787759664506),
 (520, 0.22291128503014115),
 (729, 0.22291128503014115),
 (1496, 0.22291128503014115),
 (1599, 0.22291128503014115),
 (2813, 0.22291128503014115),
 (3263, 0.22291128503014115),
 (5394, 0.22291128503014115),
 (5438, 0.22291128503014115),
 (6030, 0.22291128503014115),
 (6459, 0.22291128503014115),
 (6683, 0.22291128503014115),
 (6778, 0.22291128503014115),
 (7866, 0.22291128503014115),
 (8632, 0.22291128503014115),
 (8638, 0.22291128503014115),
 (2529, 0.22227711223719354),
 (7395, 0.22227711223719354),
 (1754, 0.2222771122371935),
 (5176, 0.2222771122371935),
 (7771, 0.2222771122371935),
 (1447, 0.2211629342323457),
 (1762, 0.2211629342323457),
 (2479, 0.2211629342323457),
 (2587, 0.2211629342323457),
 (2907, 0.2211629342323457),
 (3777, 0.2211629342323457),
 (3795, 0.2211629342323457),
 (4638, 0.2211629342323457),
 (4988, 0.2211629342323457),
 (6799, 0.2211629342323457),
 (6308, 0.22116293423234568),
 (8671, 0.21778620259218834),
 (2009, 0.2173913043478261),
 (3075, 0.2173913043478261),
 (3762, 0.2173913043478261),
 (4905, 0.2173913043478261),
 (5410, 0.2173913043478261),
 (1191, 0.21535276082326618),
 (1287, 0.21535276082326618),
 (1540, 0.21535276082326618),
 (3833, 0.21535276082326618),
 (3883, 0.21535276082326618),
 (4142, 0.21535276082326618),
 (4885, 0.21535276082326618),
 (5541, 0.21535276082326618),
 (5882, 0.21535276082326618),
 (6889, 0.21535276082326618),
 (9669, 0.21535276082326618),
 (501, 0.21281413268968719),
 (5876, 0.21281413268968719),
 (7599, 0.21281413268968719),
 (9980, 0.21281413268968719),
 (6963, 0.2114722130550724),
 (2583, 0.2085144140570748),
 (4942, 0.2085144140570748),
 (2, 0.20851441405707477),
 (32, 0.20851441405707477),
 (70, 0.20851441405707477),
 (766, 0.20851441405707477),
 (791, 0.20851441405707477),
 (797, 0.20851441405707477),
 (838, 0.20851441405707477),
 (865, 0.20851441405707477),
 (933, 0.20851441405707477),
 (1201, 0.20851441405707477),
 (1238, 0.20851441405707477),
 (1349, 0.20851441405707477),
 (1456, 0.20851441405707477),
 (1533, 0.20851441405707477),
 (1636, 0.20851441405707477),
 (1911, 0.20851441405707477),
 (1954, 0.20851441405707477),
 (2412, 0.20851441405707477),
 (2856, 0.20851441405707477),
 (2873, 0.20851441405707477),
 (3148, 0.20851441405707477),
 (3167, 0.20851441405707477),
 (3233, 0.20851441405707477),
 (3242, 0.20851441405707477),
 (3314, 0.20851441405707477),
 (4188, 0.20851441405707477),
 (4296, 0.20851441405707477),
 (4534, 0.20851441405707477),
 (5262, 0.20851441405707477),
 (5344, 0.20851441405707477),
 (5676, 0.20851441405707477),
 (5843, 0.20851441405707477),
 (5908, 0.20851441405707477),
 (6156, 0.20851441405707477),
 (6697, 0.20851441405707477),
 (7280, 0.20851441405707477),
 (7318, 0.20851441405707477),
 (7392, 0.20851441405707477),
 (7418, 0.20851441405707477),
 (7419, 0.20851441405707477),
 (8030, 0.20851441405707477),
 (8274, 0.20851441405707477),
 (8410, 0.20851441405707477),
 (8432, 0.20851441405707477),
 (9069, 0.20851441405707477),
 (9113, 0.20851441405707477),
 (9556, 0.20851441405707477),
 (7873, 0.2044652050273827),
 (9639, 0.2044652050273827),
 (4, 0.20228869496966945),
 (168, 0.20228869496966945),
 (264, 0.20228869496966945),
 (278, 0.20228869496966945),
 (477, 0.20228869496966945),
 (869, 0.20228869496966945),
 (1863, 0.20228869496966945),
 (4078, 0.20228869496966945),
 (4223, 0.20228869496966945),
 (4302, 0.20228869496966945),
 (5965, 0.20228869496966945),
 (6297, 0.20228869496966945),
 (1544, 0.20064308847628204),
 (645, 0.200643088476282),
 (26, 0.1978141420187361),
 (36, 0.1978141420187361),
 (71, 0.1978141420187361),
 (160, 0.1978141420187361),
 (531, 0.1978141420187361),
 (554, 0.1978141420187361),
 (653, 0.1978141420187361),
 (655, 0.1978141420187361),
 (779, 0.1978141420187361),
 (794, 0.1978141420187361),
 (1216, 0.1978141420187361),
 (1362, 0.1978141420187361),
 (1561, 0.1978141420187361),
 (2300, 0.1978141420187361),
 (2332, 0.1978141420187361),
 (2392, 0.1978141420187361),
 (3041, 0.1978141420187361),
 (3349, 0.1978141420187361),
 (3830, 0.1978141420187361),
 (3868, 0.1978141420187361),
 (3893, 0.1978141420187361),
 (4958, 0.1978141420187361),
 (5130, 0.1978141420187361),
 (5227, 0.1978141420187361),
 (5557, 0.1978141420187361),
 (6070, 0.1978141420187361),
 (6432, 0.1978141420187361),
 (6563, 0.1978141420187361),
 (6746, 0.1978141420187361),
 (7835, 0.1978141420187361),
 (9081, 0.1978141420187361),
 (9587, 0.1978141420187361),
 (441, 0.19702760155977517),
 (6862, 0.19702760155977517),
 (6923, 0.19702760155977517),
 (8545, 0.19702760155977517),
 (9126, 0.19702760155977517),
 (458, 0.19658927487319622),
 (608, 0.19658927487319622),
 (1135, 0.19658927487319622),
 (1901, 0.19658927487319622),
 (3268, 0.19658927487319622),
 (6405, 0.19658927487319622),
 (7166, 0.19658927487319622),
 (7533, 0.19658927487319622),
 (7756, 0.19658927487319622),
 (8989, 0.19538688270775087),
 (159, 0.19360077316559157),
 (1813, 0.19360077316559157),
 (13, 0.19134594929397594),
 (64, 0.19134594929397594),
 (1672, 0.19134594929397594),
 (2011, 0.19134594929397594),
 (2112, 0.19134594929397594),
 (4826, 0.19134594929397594),
 (5119, 0.19134594929397594),
 (8825, 0.19134594929397594),
 (8263, 0.19034674690672024),
 (170, 0.18860838403857944),
 (190, 0.18860838403857944),
 (276, 0.18860838403857944),
 (331, 0.18860838403857944),
 (384, 0.18860838403857944),
 (956, 0.18860838403857944),
 (976, 0.18860838403857944),
 (1348, 0.18860838403857944),
 (2164, 0.18860838403857944),
 (2453, 0.18860838403857944),
 (2647, 0.18860838403857944),
 (2895, 0.18860838403857944),
 (3104, 0.18860838403857944),
 (3926, 0.18860838403857944),
 (4006, 0.18860838403857944),
 (4023, 0.18860838403857944),
 (4160, 0.18860838403857944),
 (4227, 0.18860838403857944),
 (4388, 0.18860838403857944),
 (4447, 0.18860838403857944),
 (4633, 0.18860838403857944),
 (5010, 0.18860838403857944),
 (6175, 0.18860838403857944),
 (6253, 0.18860838403857944),
 (6402, 0.18860838403857944),
 (6539, 0.18860838403857944),
 (6788, 0.18860838403857944),
 (6913, 0.18860838403857944),
 (6990, 0.18860838403857944),
 (7003, 0.18860838403857944),
 (7135, 0.18860838403857944),
 (7322, 0.18860838403857944),
 (8086, 0.18860838403857944),
 (8225, 0.18860838403857944),
 (9810, 0.18860838403857944),
 (6850, 0.1872514715682846),
 (9766, 0.1872514715682846),
 (6254, 0.18725147156828456),
 (156, 0.18650096164806276),
 (164, 0.18650096164806276),
 (928, 0.18650096164806276),
 (1477, 0.18650096164806276),
 (1814, 0.18650096164806276),
 (2110, 0.18650096164806276),
 (2405, 0.18650096164806276),
 (2554, 0.18650096164806276),
 (2879, 0.18650096164806276),
 (2923, 0.18650096164806276),
 (3050, 0.18650096164806276),
 (3576, 0.18650096164806276),
 (3881, 0.18650096164806276),
 (3990, 0.18650096164806276),
 (4155, 0.18650096164806276),
 (4485, 0.18650096164806276),
 (4871, 0.18650096164806276),
 (6159, 0.18650096164806276),
 (7942, 0.18650096164806276),
 (8046, 0.18650096164806276),
 (9359, 0.18650096164806276),
 (9579, 0.18650096164806276),
 (408, 0.18430244519362143),
 (2274, 0.18430244519362143),
 (2352, 0.18430244519362143),
 (2353, 0.18430244519362143),
 (7390, 0.18430244519362143),
 (7500, 0.18430244519362143),
 (8249, 0.18430244519362143),
 (87, 0.18200630207731605),
 (217, 0.18200630207731605),
 (431, 0.18200630207731605),
 (1040, 0.18200630207731605),
 (1298, 0.18200630207731605),
 (1881, 0.18200630207731605),
 (2656, 0.18200630207731605),
 (2762, 0.18200630207731605),
 (3124, 0.18200630207731605),
 (3256, 0.18200630207731605),
 (3617, 0.18200630207731605),
 (4377, 0.18200630207731605),
 (4667, 0.18200630207731605),
 (4897, 0.18200630207731605),
 (8540, 0.18200630207731605),
 (8774, 0.18200630207731605),
 (143, 0.18057877962865385),
 (288, 0.18057877962865385),
 (290, 0.18057877962865385),
 (295, 0.18057877962865385),
 (330, 0.18057877962865385),
 (412, 0.18057877962865385),
 (488, 0.18057877962865385),
 (649, 0.18057877962865385),
 (821, 0.18057877962865385),
 (989, 0.18057877962865385),
 (1057, 0.18057877962865385),
 (1765, 0.18057877962865385),
 (2188, 0.18057877962865385),
 (2335, 0.18057877962865385),
 (2793, 0.18057877962865385),
 (2833, 0.18057877962865385),
 (2862, 0.18057877962865385),
 (2932, 0.18057877962865385),
 (3026, 0.18057877962865385),
 (3117, 0.18057877962865385),
 (3187, 0.18057877962865385),
 (3234, 0.18057877962865385),
 (3364, 0.18057877962865385),
 (3376, 0.18057877962865385),
 (3453, 0.18057877962865385),
 (4052, 0.18057877962865385),
 (4300, 0.18057877962865385),
 (4403, 0.18057877962865385),
 (4652, 0.18057877962865385),
 (4724, 0.18057877962865385),
 (5001, 0.18057877962865385),
 (5015, 0.18057877962865385),
 (5051, 0.18057877962865385),
 (5239, 0.18057877962865385),
 (5512, 0.18057877962865385),
 (5782, 0.18057877962865385),
 (6244, 0.18057877962865385),
 (6458, 0.18057877962865385),
 (6565, 0.18057877962865385),
 (6815, 0.18057877962865385),
 (6830, 0.18057877962865385),
 (7993, 0.18057877962865385),
 (8206, 0.18057877962865385),
 (8702, 0.18057877962865385),
 (8917, 0.18057877962865385),
 (9156, 0.18057877962865385),
 (9880, 0.18057877962865385),
 (2028, 0.18057877962865382),
 (9363, 0.1787266406203498),
 (336, 0.17782168978975482),
 (631, 0.17782168978975482),
 (5551, 0.17782168978975482),
 (5632, 0.17782168978975482),
 (5860, 0.17782168978975482),
 (7076, 0.17782168978975482),
 (9428, 0.17782168978975482),
 (8108, 0.17622684421256035),
 (6664, 0.17622684421256032),
 (845, 0.1739130434782609),
 (1430, 0.1739130434782609),
 (1537, 0.1739130434782609),
 (1792, 0.1739130434782609),
 (2712, 0.1739130434782609),
 (2829, 0.1739130434782609),
 (2936, 0.1739130434782609),
 (4848, 0.1739130434782609),
 (5251, 0.1739130434782609),
 (6531, 0.1739130434782609),
 (6892, 0.1739130434782609),
 (7461, 0.1739130434782609),
 (8950, 0.1739130434782609),
 (9789, 0.1739130434782609),
 (7677, 0.17376201171422898),
 (133, 0.17349447958987207),
 (138, 0.17349447958987207),
 (148, 0.17349447958987207),
 (1503, 0.17349447958987207),
 (1598, 0.17349447958987207),
 (1775, 0.17349447958987207),
 (2200, 0.17349447958987207),
 (2209, 0.17349447958987207),
 (2500, 0.17349447958987207),
 (2556, 0.17349447958987207),
 (2988, 0.17349447958987207),
 (3064, 0.17349447958987207),
 (3164, 0.17349447958987207),
 (3296, 0.17349447958987207),
 (3412, 0.17349447958987207),
 (3420, 0.17349447958987207),
 (3786, 0.17349447958987207),
 (3841, 0.17349447958987207),
 (3973, 0.17349447958987207),
 (4884, 0.17349447958987207),
 (5994, 0.17349447958987207),
 (6072, 0.17349447958987207),
 (6262, 0.17349447958987207),
 (6351, 0.17349447958987207),
 (6587, 0.17349447958987207),
 (6721, 0.17349447958987207),
 (6974, 0.17349447958987207),
 (7255, 0.17349447958987207),
 (7263, 0.17349447958987207),
 (7411, 0.17349447958987207),
 (7493, 0.17349447958987207),
 (8085, 0.17349447958987207),
 (8173, 0.17349447958987207),
 (8571, 0.17349447958987207),
 (8684, 0.17349447958987207),
 (9066, 0.17349447958987207),
 (9516, 0.17349447958987207),
 (46, 0.17025130615174974),
 (50, 0.17025130615174974),
 (208, 0.17025130615174974),
 (313, 0.17025130615174974),
 (619, 0.17025130615174974),
 (718, 0.17025130615174974),
 (727, 0.17025130615174974),
 (1252, 0.17025130615174974),
 (1500, 0.17025130615174974),
 (1548, 0.17025130615174974),
 (1555, 0.17025130615174974),
 (1715, 0.17025130615174974),
 (1822, 0.17025130615174974),
 (2036, 0.17025130615174974),
 (2528, 0.17025130615174974),
 (2553, 0.17025130615174974),
 (2571, 0.17025130615174974),
 (2695, 0.17025130615174974),
 (2727, 0.17025130615174974),
 (2853, 0.17025130615174974),
 (2870, 0.17025130615174974),
 (3013, 0.17025130615174974),
 (3283, 0.17025130615174974),
 (3577, 0.17025130615174974),
 (3690, 0.17025130615174974),
 (3789, 0.17025130615174974),
 (3826, 0.17025130615174974),
 (3989, 0.17025130615174974),
 (4527, 0.17025130615174974),
 (4840, 0.17025130615174974),
 (4858, 0.17025130615174974),
 (4875, 0.17025130615174974),
 (5089, 0.17025130615174974),
 (5090, 0.17025130615174974),
 (5973, 0.17025130615174974),
 (5995, 0.17025130615174974),
 (6004, 0.17025130615174974),
 (6329, 0.17025130615174974),
 (7000, 0.17025130615174974),
 (7259, 0.17025130615174974),
 (7325, 0.17025130615174974),
 (7891, 0.17025130615174974),
 (8265, 0.17025130615174974),
 (8270, 0.17025130615174974),
 (8516, 0.17025130615174974),
 (9082, 0.17025130615174974),
 (9679, 0.17025130615174974),
 (3292, 0.1691275228729346),
 (10, 0.16718346377260587),
 (28, 0.16718346377260587),
 (344, 0.16718346377260587),
 (391, 0.16718346377260587),
 (634, 0.16718346377260587),
 (652, 0.16718346377260587),
 (1291, 0.16718346377260587),
 (1449, 0.16718346377260587),
 (1611, 0.16718346377260587),
 (1752, 0.16718346377260587),
 (1771, 0.16718346377260587),
 (1828, 0.16718346377260587),
 (1830, 0.16718346377260587),
 (1870, 0.16718346377260587),
 (1958, 0.16718346377260587),
 (1976, 0.16718346377260587),
 (1995, 0.16718346377260587),
 (2106, 0.16718346377260587),
 (2161, 0.16718346377260587),
 (2230, 0.16718346377260587),
 (2330, 0.16718346377260587),
 (2620, 0.16718346377260587),
 (2719, 0.16718346377260587),
 (3250, 0.16718346377260587),
 (3330, 0.16718346377260587),
 (3413, 0.16718346377260587),
 (3621, 0.16718346377260587),
 (4036, 0.16718346377260587),
 (4056, 0.16718346377260587),
 (4141, 0.16718346377260587),
 (4317, 0.16718346377260587),
 (4508, 0.16718346377260587),
 (5380, 0.16718346377260587),
 (5574, 0.16718346377260587),
 (5581, 0.16718346377260587),
 (5592, 0.16718346377260587),
 (5844, 0.16718346377260587),
 (6229, 0.16718346377260587),
 (6852, 0.16718346377260587),
 (7081, 0.16718346377260587),
 (7196, 0.16718346377260587),
 (8079, 0.16718346377260587),
 (9077, 0.16718346377260587),
 (9124, 0.16718346377260587),
 (9173, 0.16718346377260587),
 (9321, 0.16718346377260587),
 (9953, 0.16718346377260587),
 (9998, 0.16718346377260587),
 (6964, 0.16694514082354447),
 (4071, 0.16694514082354445),
 (822, 0.16681153124565984),
 (846, 0.16681153124565984),
 (848, 0.16681153124565984),
 (2966, 0.16681153124565984),
 (3664, 0.16681153124565984),
 (3964, 0.16681153124565984),
 (5189, 0.16681153124565984),
 (5224, 0.16681153124565984),
 (6948, 0.16681153124565984),
 (7581, 0.16681153124565984),
 (7792, 0.16681153124565984),
 (8439, 0.16681153124565984),
 (8538, 0.16681153124565984),
 (316, 0.16357216402190616),
 (903, 0.16357216402190616),
 (1020, 0.16357216402190616),
 (1490, 0.16357216402190616),
 (1860, 0.16357216402190616),
 (2310, 0.16357216402190616),
 (3299, 0.16357216402190616),
 (4548, 0.16357216402190616),
 (6785, 0.16357216402190616),
 (7154, 0.16357216402190616),
 (7871, 0.16357216402190616),
 (8799, 0.16357216402190616),
 (135, 0.16357216402190614),
 (8818, 0.16287758693937096),
 (7, 0.16151457061744964),
 (112, 0.16151457061744964),
 (511, 0.16151457061744964),
 (547, 0.16151457061744964),
 (731, 0.16151457061744964),
 (798, 0.16151457061744964),
 (819, 0.16151457061744964),
 (984, 0.16151457061744964),
 (1120, 0.16151457061744964),
 (1145, 0.16151457061744964),
 (1255, 0.16151457061744964),
 (1489, 0.16151457061744964),
 (1573, 0.16151457061744964),
 (1617, 0.16151457061744964),
 (1717, 0.16151457061744964),
 (2113, 0.16151457061744964),
 (2136, 0.16151457061744964),
 (2160, 0.16151457061744964),
 (2219, 0.16151457061744964),
 (2472, 0.16151457061744964),
 (2726, 0.16151457061744964),
 (2825, 0.16151457061744964),
 (2877, 0.16151457061744964),
 (3118, 0.16151457061744964),
 (3171, 0.16151457061744964),
 (3182, 0.16151457061744964),
 (3235, 0.16151457061744964),
 (3458, 0.16151457061744964),
 (3600, 0.16151457061744964),

In [36]:
## top 5 movies related to Shawshank Redemption
for i in dist[0:5]:
  print(movies_new.iloc[i[0]].title)

The Shawshank Redemption
Brubaker
Cool Hand Luke
A Prophet
The Getaway

In [39]:
# Function to recommend to 5 related movies
def recommend(movie):
  index = movies_new[movies_new['title'] == movie].index[0]
  distance = sorted(list(enumerate(sim[index])), reverse=True, key=lambda vec:vec[1])
  for i in distance[0:5]:
    print(movies_new.iloc[i[0]].title)

In [40]:
recommend('Iron Man')

Iron Man
Guardians of the Galaxy Vol. 2
Star Wars: Episode III - Revenge of the Sith
G.O.R.A.
Everything Everywhere All at Once